server:
  port: 8000 # 项目启动的端口


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

#mybatis:
#  # MyBatis xml 配置文件路径
#  mapper-locations: classpath:/mapper/**/*.xml
